const SET_QUERY_INPUT = 'SET_QUERY_INPUT';

const FORMAT_QUERY = 'FORMAT_QUERY';

const TOGGLE_SHOULD_SHOW_ADVANCED_OPTIONS =
  'TOGGLE_SHOULD_SHOW_ADVANCED_OPTIONS';

const SET_INDENTATION = 'SET_INDENTATION';

const SET_MAX_LINE_LENGTH = 'SET_MAX_LINE_LENGTH';

const SET_SHOULD_PLACE_DOTS_AFTER_LINE_BREAKS =
  'SET_SHOULD_PLACE_DOTS_AFTER_LINE_BREAKS';

module.exports = {
  SET_QUERY_INPUT,
  FORMAT_QUERY,
  TOGGLE_SHOULD_SHOW_ADVANCED_OPTIONS,
  SET_INDENTATION,
  SET_MAX_LINE_LENGTH,
  SET_SHOULD_PLACE_DOTS_AFTER_LINE_BREAKS,
};
